#include "Model.h"

Model::Model(Configuration &config, int _uniqueId)
    : uniqueId(_uniqueId),
      buMean(("buMean_" + std::to_string(uniqueId)).c_str(), "", 5.2819e+03,
             5250, 5290),
      buSigma(("buSigma_" + std::to_string(uniqueId)).c_str(), "", 20, 10, 50),
      buA1(("buA1_" + std::to_string(uniqueId)).c_str(), "", 1, 0, 5),
      buN1(("buN1_" + std::to_string(uniqueId)).c_str(), "", 10),
      buA2(("buA2_" + std::to_string(uniqueId)).c_str(), "", -1, -5, -0.00001),
      buN2(("buN2_" + std::to_string(uniqueId)).c_str(), "", 10),
      buFrac(("buFrac_" + std::to_string(uniqueId)).c_str(), "", 2.0967e-01, 0,
             1),
      buPdf1(("buPdf1_" + std::to_string(uniqueId)).c_str(), "", config.buMass,
             buMean, buSigma, buA1, buN1),
      buPdf2(("buPdf2_" + std::to_string(uniqueId)).c_str(), "", config.buMass,
             buMean, buSigma, buA2, buN2),
      buPdf(("buPdf_" + std::to_string(uniqueId)).c_str(), "",
            RooArgSet(buPdf1, buPdf2), buFrac),
      deltaMean(("deltaMean_" + std::to_string(uniqueId)).c_str(), "", 143, 136,
                160),
      deltaSigma(("deltaSigma_" + std::to_string(uniqueId)).c_str(), "", 2, 0,
                 10),
      deltaA1(("deltaA1_" + std::to_string(uniqueId)).c_str(), "", 1, 0, 5),
      deltaN1(("deltaN1_" + std::to_string(uniqueId)).c_str(), "", 10),
      deltaA2(("deltaA2_" + std::to_string(uniqueId)).c_str(), "", -1, -5,
              -0.00001),
      deltaN2(("deltaN2_" + std::to_string(uniqueId)).c_str(), "", 10),
      deltaFrac(("deltaFrac_" + std::to_string(uniqueId)).c_str(), "", 0.5, 0,
                1),
      deltaPdf1(("deltaPdf1_" + std::to_string(uniqueId)).c_str(), "",
                config.deltaMass, deltaMean, deltaSigma, deltaA1, deltaN1),
      deltaPdf2(("deltaPdf2_" + std::to_string(uniqueId)).c_str(), "",
                config.deltaMass, deltaMean, deltaSigma, deltaA2, deltaN2),
      deltaPdf(("deltaPdf_" + std::to_string(uniqueId)).c_str(), "",
               RooArgSet(deltaPdf1, deltaPdf2), deltaFrac) {}
