all:
	# c++ -std=c++11 -O3 -march=native -Wall -Wextra -lTreePlayer -lFoam -lXMLIO -lRooFitCore -lRooFit -lMinuit `root-config --cflags --libs` SimToy2D_SaveDataSet_old.cpp -o SimToy2D_SaveDataSet_old 
	c++ -std=c++11 -O3 -march=native -Wall -Wextra -lTreePlayer -lFoam -lXMLIO -lRooFitCore -lRooFit -lMinuit `root-config --cflags --libs` SimToy1D_ReadDataSet_old.cpp -o SimToy1D_ReadDataSet_old 
