# all:
all:
	c++ -std=c++11 -O3 -march=native -Wall -Wextra -lTreePlayer -lFoam -lXMLIO -lRooFitCore -lRooFit -lMinuit `root-config --cflags --libs` RooCruijff.cpp SimToy1D_ReadSaveDataSet.cpp -o SimToy1D_ReadSaveDataSet 
